pub const WORD_TABLE: [&str; 100] = [
    "saw",     // 00
    "seat",    // 01
    "sun",     // 02
    "sum",     // 03
    "sour",    // 04
    "seal",    // 05
    "sage",    // 06
    "sock",    // 07
    "safe",    // 08
    "soap",    // 09
    "dice",    // 10
    "dot",     // 11
    "den",     // 12
    "dome",    // 13
    "door",    // 14
    "doll",    // 15
    "dish",    // 16
    "duck",    // 17
    "dove",    // 18
    "tape",    // 19
    "nose",    // 20
    "net",     // 21
    "nun",     // 22
    "name",    // 23
    "narrate", // 24
    "nail",    // 25
    "niche",   // 26
    "neck",    // 27
    "knife",   // 28
    "nap",     // 29
    "mouse",   // 30
    "mat",     // 31
    "moon",    // 32
    "mummy",   // 33
    "mirror",  // 34
    "mule",    // 35
    "match",   // 36
    "mug",     // 37
    "movie",   // 38
    "map",     // 39
    "rose",    // 40
    "rat",     // 41
    "rain",    // 42
    "ram",     // 43
    "roar",    // 44
    "rail",    // 45
    "roach",   // 46
    "rock",    // 47
    "roof",    // 48
    "rope",    // 49
    "lace",    // 50
    "lot",     // 51
    "lion",    // 52
    "lime",    // 53
    "lure",    // 54
    "lily",    // 55
    "leech",   // 56
    "lock",    // 57
    "leaf",    // 58
    "lip",     // 59
    "juice",   // 60
    "jet",     // 61
    "chain",   // 62
    "jam",     // 63
    "jar",     // 64
    "jewel",   // 65
    "judge",   // 66
    "chalk",   // 67
    "chef",    // 68
    "jeep",    // 69
    "case",    // 70
    "cat",     // 71
    "coin",    // 72
    "comb",    // 73
    "car",     // 74
    "coal",    // 75
    "cage",    // 76
    "cake",    // 77
    "cave",    // 78
    "cap",     // 79
    "face",    // 80
    "foot",    // 81
    "fan",     // 82
    "foam",    // 83
    "fire",    // 84
    "file",    // 85
    "fish",    // 86
    "fog",     // 87
    "fife",    // 88
    "fob",     // 89
    "bus",     // 90
    "bat",     // 91
    "bone",    // 92
    "bum",     // 93
    "bear",    // 94
    "bell",    // 95
    "beach",   // 96
    "book",    // 97
    "beef",    // 98
    "pipe"     // 99
];